### ISSUE TITLE
1.2.14（183）版本软件闪退

### ISSUE THREAD

**Issue by Darkoutput** [paynexss/Scripts#1]
![image](https://user-images.githubusercontent.com/77570061/226165291-73c87ece-4653-47be-b934-8c8348d6e5e0.jpeg)
圈X添加了两个FileBall的重写，点击软件就会闪退，大佬你破的是哪个版本的，可以告诉一下吗？

**Comment by paynexss** [comment]
https://t.me/helloworld_1024/1180
